In [2]:
from scipy.misc import imread
import pandas as pd
import numpy as np
import glob
import re

In [13]:
# flatten in imread set to true, images loaded as gray scale
row = 0
image_data = pd.DataFrame(columns=("image", "timestamp"))

for path in sorted(glob.glob("./katkam-scaled/*")):
    
    matches = re.search("\d+", path)
    image_data.loc[row] = [imread(path, flatten=True).flatten(), matches.group()]
    row += 1

image_data["timestamp"] = pd.to_datetime(image_data["timestamp"])

In [3]:
# get list of weather data csv files
files = [f for f in sorted(glob.glob("./yvr-weather/*"))]

In [8]:
def CleanWeatherData(weather_data):
    # data quality <-- look at later? 
    weather_data.drop(["Year","Month","Day","Time","Temp Flag", "Dew Point Temp Flag",
                       "Rel Hum Flag", "Wind Dir Flag", "Wind Spd Flag",
                       "Visibility Flag", "Stn Press Flag",
                       "Hmdx Flag", "Wind Chill Flag", "Hmdx", "Wind Chill",
                       "Data Quality"], axis=1, inplace=True)
    weather_data.rename(columns={'Date/Time':'timestamp'}, inplace=True)
    
filename = files[1]
weather_data = pd.read_csv(filename, sep=',', skiprows=16, parse_dates=[0])
CleanWeatherData(weather_data)

In [9]:
print(weather_data[weather_data["Weather"] == "Drizzle"])

no_drizzle = "(,Drizzle)?(Drizzle,)?(Drizzle)?"
weather["Weather"] = weather["Weather"].str.replace(no_drizzle, "")
weather["Weather"].replace("", np.nan, inplace=True)

print(weather_data)

,timestamp,Temp (°C),Dew Point Temp (°C),Rel Hum (%),Wind Dir (10s deg),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
159,2016-07-07 15:00:00,17.1,14.4,84,13,19,24.1,101.17,Drizzle
368,2016-07-16 08:00:00,16.0,14.0,88,11,13,24.1,101.74,Drizzle

In [46]:
#Takes the original weather data 
#Split the data into 
def dataFrame2Array(images, train_set):
    # reshape to (_,49152) (192x256 image to 1-d)
    
    for i in range(train_set.shape[0]):
        images[i] = train_set.image.iloc[i] / 255
    
    
def splitDataWithNanValues(images, weather):
    
    #Split into non null and null
    train = weather[~weather["Weather"].isnull()]
    test = weather[weather["Weather"].isnull()]

    train_times = list(train.timestamp.map(lambda x: x))
    test_times = list(test.timestamp.map(lambda x: x))
    
    img_train = images[images.timestamp.isin(train_times)]
    img_test = images[images.timestamp.isin(test_times)]
    
    train_img_times = list(img_train.timestamp.map(lambda x: x))
    test_img_times = list(img_test.timestamp.map(lambda x: x))
    
    y_train = train[train.timestamp.isin(train_img_times)]
    y_test = test[test.timestamp.isin(test_img_times)]
    
    X_train = np.zeros((img_train.shape[0],49152), dtype=np.float32)
    X_test = np.zeros((img_test.shape[0],49152), dtype=np.float32)
    
    dataFrame2Array(X_train, img_train)
    dataFrame2Array(X_test, img_test)
    
    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = splitDataWithNanValues(image_data,
                                                         weather_data)

In [48]:


from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train.Weather)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [49]:
model.predict(X_test)

array(['Clear', 'Mainly Clear', 'Mostly Cloudy', 'Clear', 'Clear', 'Clear',
       'Mainly Clear', 'Mostly Cloudy', 'Cloudy', 'Mostly Cloudy',
       'Mostly Cloudy', 'Mostly Cloudy', 'Mainly Clear', 'Mainly Clear',
       'Cloudy', 'Mostly Cloudy', 'Cloudy', 'Cloudy', 'Clear',
       'Mainly Clear', 'Mostly Cloudy', 'Mostly Cloudy', 'Mostly Cloudy',
       'Mainly Clear', 'Clear', 'Clear', 'Clear', 'Mostly Cloudy',
       'Mostly Cloudy', 'Mostly Cloudy', 'Cloudy', 'Rain', 'Cloudy',
       'Rain Showers', 'Cloudy', 'Cloudy', 'Cloudy', 'Rain', 'Cloudy',
       'Clear', 'Mainly Clear', 'Mostly Cloudy', 'Mostly Cloudy', 'Rain',
       'Cloudy', 'Cloudy', 'Cloudy', 'Cloudy', 'Mostly Cloudy',
       'Mostly Cloudy', 'Mostly Cloudy', 'Cloudy', 'Mostly Cloudy',
       'Mostly Cloudy', 'Rain Showers', 'Rain', 'Mostly Cloudy', 'Rain',
       'Rain', 'Rain', 'Mostly Cloudy', 'Mainly Clear', 'Cloudy',
       'Mostly Cloudy', 'Mostly Cloudy', 'Rain', 'Rain', 'Rain',
       'Mostly Cloudy', 'Mostly Cloudy', 'Cloudy', 'Mostly Cloudy',
       'Rain Showers', 'Mostly Cloudy', 'Mostly Cloudy', 'Rain Showers',
       'Rain', 'Cloudy', 'Cloudy', 'Mostly Cloudy', 'Clear', 'Clear',
       'Cloudy', 'Mostly Cloudy', 'Rain Showers', 'Mainly Clear', 'Cloudy',
       'Mostly Cloudy', 'Rain', 'Rain Showers', 'Mainly Clear',
       'Mostly Cloudy', 'Mainly Clear', 'Rain Showers', 'Cloudy', 'Cloudy',
       'Cloudy', 'Rain', 'Cloudy', 'Rain', 'Mostly Cloudy',
       'Mostly Cloudy', 'Clear', 'Rain Showers', 'Mostly Cloudy', 'Cloudy',
       'Rain', 'Cloudy', 'Clear', 'Clear', 'Clear', 'Mainly Clear',
       'Mostly Cloudy', 'Mostly Cloudy', 'Mostly Cloudy', 'Mostly Cloudy',
       'Cloudy', 'Cloudy', 'Mainly Clear', 'Clear', 'Mostly Cloudy',
       'Mostly Cloudy', 'Cloudy', 'Rain', 'Clear', 'Mainly Clear',
       'Mainly Clear', 'Mainly Clear', 'Mainly Clear', 'Mainly Clear',
       'Clear', 'Clear', 'Mainly Clear', 'Mostly Cloudy', 'Rain', 'Rain',
       'Cloudy', 'Rain', 'Mostly Cloudy', 'Cloudy', 'Cloudy',
       'Mostly Cloudy', 'Clear', 'Mainly Clear', 'Mostly Cloudy',
       'Mostly Cloudy', 'Clear', 'Mostly Cloudy', 'Mainly Clear',
       'Mostly Cloudy', 'Cloudy', 'Cloudy', 'Cloudy', 'Cloudy',
       'Mostly Cloudy', 'Mostly Cloudy', 'Mostly Cloudy', 'Mostly Cloudy',
       'Cloudy', 'Cloudy', 'Cloudy', 'Cloudy', 'Cloudy', 'Cloudy',
       'Mostly Cloudy', 'Rain', 'Mostly Cloudy', 'Rain', 'Cloudy',
       'Cloudy', 'Cloudy', 'Mostly Cloudy', 'Mostly Cloudy',
       'Mostly Cloudy', 'Cloudy', 'Cloudy', 'Cloudy', 'Cloudy', 'Clear',
       'Rain', 'Cloudy', 'Mainly Clear', 'Cloudy', 'Rain Showers', 'Rain',
       'Cloudy', 'Cloudy', 'Cloudy', 'Mostly Cloudy', 'Cloudy',
       'Mostly Cloudy', 'Clear', 'Mostly Cloudy', 'Rain', 'Rain', 'Rain',
       'Rain', 'Cloudy', 'Cloudy', 'Mainly Clear', 'Mostly Cloudy',
       'Mostly Cloudy', 'Clear', 'Mostly Cloudy', 'Mostly Cloudy', 'Clear',
       'Mainly Clear', 'Mainly Clear', 'Mainly Clear', 'Clear', 'Clear',
       'Clear', 'Clear', 'Mainly Clear', 'Mostly Cloudy', 'Mostly Cloudy',
       'Mostly Cloudy', 'Mainly Clear', 'Mainly Clear', 'Clear', 'Clear',
       'Mostly Cloudy', 'Cloudy', 'Clear', 'Clear', 'Mostly Cloudy',
       'Mostly Cloudy', 'Clear', 'Clear', 'Clear', 'Clear', 'Clear',
       'Clear', 'Clear', 'Clear', 'Mainly Clear', 'Mostly Cloudy',
       'Mostly Cloudy', 'Clear', 'Mainly Clear', 'Clear', 'Clear', 'Clear',
       'Clear', 'Clear', 'Clear', 'Mainly Clear', 'Mostly Cloudy',
       'Mostly Cloudy', 'Mostly Cloudy', 'Cloudy', 'Cloudy',
       'Mostly Cloudy', 'Clear', 'Mostly Cloudy', 'Mostly Cloudy',
       'Mostly Cloudy', 'Mainly Clear', 'Mostly Cloudy', 'Mostly Cloudy'], dtype=object)

In [51]:
y_test

,timestamp,Temp (°C),Dew Point Temp (°C),Rel Hum (%),Wind Dir (10s deg),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
102,2016-06-05 06:00:00,17.7,15.2,85.0,29.0,17.0,48.3,101.30,NaN
104,2016-06-05 08:00:00,19.6,15.5,77.0,30.0,27.0,48.3,101.31,NaN
105,2016-06-05 09:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,2016-06-05 11:00:00,22.6,17.0,70.0,29.0,21.0,48.3,101.27,NaN
108,2016-06-05 12:00:00,23.5,15.9,62.0,30.0,24.0,48.3,101.24,NaN
110,2016-06-05 14:00:00,24.4,16.3,60.0,29.0,18.0,48.3,101.14,NaN
111,2016-06-05 15:00:00,24.7,16.6,60.0,29.0,11.0,48.3,101.09,NaN
113,2016-06-05 17:00:00,22.5,15.7,65.0,27.0,11.0,48.3,101.00,NaN
114,2016-06-05 18:00:00,22.3,15.5,65.0,24.0,3.0,48.3,100.96,NaN
116,2016-06-05 20:00:00,20.0,15.5,75.0,20.0,6.0,48.3,100.97,NaN
117,2016-06-05 21:00:00,20.2,15.1,72.0,1.0,4.0,48.3,100.99,NaN
126,2016-06-06 06:00:00,17.9,15.7,87.0,31.0,8.0,48.3,101.22,NaN
128,2016-06-06 08:00:00,19.6,14.9,74.0,30.0,22.0,48.3,101.28,NaN
129,2016-06-06 09:00:00,20.5,14.9,70.0,29.0,21.0,48.3,101.28,NaN
131,2016-06-06 11:00:00,19.9,14.4,70.0,30.0,19.0,48.3,101.24,NaN
132,2016-06-06 12:00:00,19.9,14.8,72.0,30.0,16.0,48.3,101.23,NaN
134,2016-06-06 14:00:00,22.9,13.5,55.0,23.0,8.0,48.3,101.16,NaN
135,2016-06-06 15:00:00,22.7,13.1,54.0,22.0,7.0,48.3,101.09,NaN
137,2016-06-06 17:00:00,24.0,12.2,47.0,26.0,9.0,48.3,100.98,NaN
138,2016-06-06 18:00:00,20.9,13.2,61.0,25.0,10.0,48.3,100.93,NaN
140,2016-06-06 20:00:00,17.9,13.9,77.0,22.0,4.0,48.3,100.92,NaN
141,2016-06-06 21:00:00,16.7,13.7,82.0,28.0,3.0,48.3,100.93,NaN
150,2016-06-07 06:00:00,15.1,12.3,83.0,10.0,11.0,48.3,101.00,NaN
152,2016-06-07 08:00:00,17.8,14.0,78.0,22.0,10.0,48.3,100.98,NaN
153,2016-06-07 09:00:00,18.1,13.9,76.0,23.0,12.0,48.3,100.98,NaN
155,2016-06-07 11:00:00,19.1,14.4,74.0,24.0,10.0,48.3,100.96,NaN
156,2016-06-07 12:00:00,19.2,14.3,73.0,24.0,13.0,48.3,100.95,NaN
158,2016-06-07 14:00:00,21.1,12.9,59.0,22.0,10.0,48.3,100.87,NaN
159,2016-06-07 15:00:00,22.2,16.3,69.0,27.0,11.0,48.3,100.81,NaN
161,2016-06-07 17:00:00,21.4,14.7,65.0,22.0,11.0,48.3,100.71,NaN
...,...,...,...,...,...,...,...,...,...
659,2016-06-28 11:00:00,19.9,14.8,72.0,23.0,18.0,48.3,102.14,NaN
660,2016-06-28 12:00:00,19.2,15.1,77.0,23.0,16.0,48.3,102.07,NaN
662,2016-06-28 14:00:00,19.5,15.4,77.0,24.0,14.0,48.3,102.00,NaN
663,2016-06-28 15:00:00,20.0,15.7,76.0,24.0,14.0,48.3,101.96,NaN
665,2016-06-28 17:00:00,21.5,15.7,69.0,21.0,12.0,48.3,101.83,NaN
666,2016-06-28 18:00:00,22.0,15.0,64.0,20.0,12.0,48.3,101.81,NaN
668,2016-06-28 20:00:00,19.7,14.2,70.0,10.0,14.0,48.3,101.84,NaN
669,2016-06-28 21:00:00,18.2,14.0,76.0,9.0,13.0,48.3,101.88,NaN
678,2016-06-29 06:00:00,15.1,13.0,87.0,9.0,14.0,32.2,102.10,NaN
680,2016-06-29 08:00:00,17.0,13.2,78.0,12.0,15.0,48.3,102.14,NaN
681,2016-06-29 09:00:00,18.1,13.0,72.0,14.0,14.0,48.3,102.14,NaN
683,2016-06-29 11:00:00,20.6,14.4,67.0,13.0,9.0,48.3,102.09,NaN
684,2016-06-29 12:00:00,18.9,15.2,79.0,22.0,21.0,48.3,102.04,NaN
686,2016-06-29 14:00:00,22.9,14.9,60.0,15.0,14.0,48.3,101.96,NaN
687,2016-06-29 15:00:00,23.6,15.3,59.0,16.0,14.0,48.3,101.91,NaN
689,2016-06-29 17:00:00,22.8,14.5,59.0,13.0,14.0,48.3,101.85,NaN
690,2016-06-29 18:00:00,21.1,13.4,61.0,14.0,18.0,48.3,101.83,NaN
692,2016-06-29 20:00:00,16.9,11.9,72.0,13.0,23.0,48.3,101.86,NaN
693,2016-06-29 21:00:00,15.5,11.1,75.0,11.0,25.0,48.3,101.90,NaN
702,2016-06-30 06:00:00,14.3,10.9,80.0,11.0,17.0,32.2,102.17,NaN
704,2016-06-30 08:00:00,16.2,11.6,74.0,11.0,13.0,32.2,102.23,NaN
705,2016-06-30 09:00:00,17.3,11.6,69.0,11.0,13.0,32.2,102.25,NaN
707,2016-06-30 11:00:00,18.8,12.2,65.0,19.0,9.0,32.2,102.23,NaN
708,2016-06-30 12:00:00,20.0,14.2,69.0,26.0,9.0,48.3,102.19,NaN
710,2016-06-30 14:00:00,19.3,14.6,74.0,23.0,20.0,48.3,102.10,NaN
711,2016-06-30 15:00:00,19.0,13.9,72.0,22.0,20.0,48.3,102.06,NaN
713,2016-06-30 17:00:00,20.4,13.5,64.0,21.0,16.0,48.3,101.95,NaN
714,2016-06-30 18:00:00,20.6,12.9,61.0,18.0,10.0,48.3,101.92,NaN
716,2016-06-30 20:00:00,17.6,11.9,69.0,13.0,14.0,48.3,101.87,NaN
717,2016-06-30 21:00:00,16.7,12.1,74.0,11.0,17.0,48.3,101.90,NaN

### Notes
- try black and white images
- try rgb images
- try other color coding images
- https://datascience.stackexchange.com/questions/5224/how-to-prepare-augment-images-for-neural-network
- use temp, dew point, ... etc to estimate weather conditions

Try:
1. remove nan data -> use for testing
2. impute nan weather data -> compare to #1